- modules/common/namespace/outputs.tf
- stacks/environment-aws/variables.tf
Add a depends on in the output so that the module ensures the role binding for tiller is maintained
> Missing dep

- modules/lead/product/jenkins-values.tpl
jenkins container was being restarted in the middle creating product because readiness + liveness tests were failing
> increase jenkins readiness time

- modules/lead/product/production.tf
- modules/lead/product/staging.tf
This PR adds permissions for the default service account to get `pod` and `job` resources.
> Added role and role binding permissions for default Service Account

- modules/lead/product/production.tf
- modules/lead/product/staging.tf
This PR should contain fixes so that the `default-staging` and `default-production` role bindings reference the correct role. Also the `list` verb has been added to the role to allow listing pods and jobs.
> Added list verb and updated role reference

- modules/lead/product/production.tf
- modules/lead/product/staging.tf
This PR replaces default staging and productions `role_ref`s with variables to prevent race conditions when Terraform creates the roles.
> Updated default role ref

- .gitignore
- modules/lead/product/jenkins-values.tpl
PV's shouldn't be needed since jobs are coming from config-as-code
> disabled jenkins persistence

- modules/common/namespace/main.tf
This PR gives permission to interact with Flagger and HPA resources to the `tiller-manager` role. This will allow users to define and perform Canary deployments.
> Allow tiller-manager to access resources for canary deployments

- modules/lead/product/jenkins-values.tpl
This allows for a pod to stick around to allow jenkins to have an
executor that can perform slack feedback quickly
> Set idle time for skaffold pod

- stacks/environment-local/variables.tf
Version 0.2.22 operator-toolchain charts don't exist anymore so terragrunt apply fails when running locally
> bump sdm_version in environment-local

- modules/lead/product/production.tf
right now, production deployments will fail since the `initContainers` that run `kubectl wait` don't have permissions to get pods in the namespace. this is because the production rolebinding references the staging namespace for the subject, so the default service account in production has no permissions.
> fix: production rolebinding references staging namespace

- Makefile
- modules/lead/toolchain/keycloak.tf
I'll have a more permanent fix when I get a response to https://github.com/hashicorp/terraform-plugin-sdk/issues/216.
The `client_timeout` provider attribute was added in 1.11, so I bumped that so it could be used since the instance of Keycloak running locally can be a bit slow at times.
> fix: don't use auth for keycloak SMTP locally, bump timeout to 15 seconds

- stacks/environment-aws/lead.tf
this appears to be the only task left for ENG-1195.  I believe that this will require a manual run of `helm del  --purge` before this can be deployed
> [ENG-1195] bump cluster-autoscaler version to 6.0.1

- modules/lead/infrastructure/main.tf
installing the latest version of cluster-autoscaler yields this error:
```
release cluster-autoscaler failed: clusterroles.rbac.authorization.k8s.io "cluster-autoscaler-aws-cluster-autoscaler" is forbidden: user "system:serviceaccount:lead-system:tiller" (groups=["system:serviceaccounts" "system:serviceaccounts:lead-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["storage.k8s.io"], Resources:["csinodes"], Verbs:["watch" "list" "get"]}
```
> [ENG-1195] allow tiller service account to view csinodes

- stacks/environment-aws/eks.tf
- stacks/environment-aws/iam.tf
version `6.0.2` for the eks module added variables `manage_worker_autoscaling_policy` and `attach_worker_autoscaling_policy` which allows us to have better control over how the cluster autoscaler IAM policy is defined / attached.
by setting `manage_worker_autoscaling_policy` to `true` and `attach_worker_autoscaling_policy` to `false`, the EKS module will still manage the contents of the policy for us without attaching it to the worker nodes, allowing us to attach it to the cluster autoscaler service account instead.
> [ENG 1195] allow EKS module to manage cluster autoscaler IAM without attaching to worker nodes

- stacks/environment-aws/variables.tf
we run out of resources to schedule converge jobs really quickly with only 5 x t3.small instances. i think 10 is a better default here
> raise essential asg max -> 10

- modules/lead/product/jenkins-values.tpl
This gets around the artifactory permission error by non persisting the image cacheing on the agent and forcing rebuild.
Downside is consecutive builds may take longer.
> do not persist agent pods

- stacks/environment-aws/iam.tf
Allow the IAM role to delete objects in the specified s3 bucket
> Add DeleteObject to operator-jenkins policy

- modules/lead/toolchain/artifactory.tf
I'm proposing that we `ignore_changes` for the Artifactory helm release. If we do make changes like expand a volume, this causes issues for re-applying the helm configuration. Additionally, if we wanted to do something like upgrade the Artifactory version while retaining the existing data, we would likely not do that through Helm.
> ignore_changes for artifactory helm release

- modules/common/cert-issuer/helm/cert-manager-issuers/templates/issuer.yaml
- modules/common/cert-issuer/helm/cert-manager-issuers/values.yaml
- modules/common/cert-issuer/issuer-values.tpl
- modules/common/cert-issuer/main.tf
- modules/common/cert-issuer/variables.tf
- modules/common/istio/main.tf
- modules/common/istio/variables.tf
- stacks/environment-aws/istio.tf
- stacks/environment-local/istio.tf
I need this to run cert-manager locally with my personal domain which uses GCP CloudDNS
> update cert-issuer module to work with GCP DNS

- modules/common/istio/istio-values.tpl
this update fixes the issues with searching spans in jaeger
> bump jaeger version to 1.16

- modules/common/namespace/main.tf
- modules/common/namespace/variables.tf
setting a max on limits and requests protects us from killing pods by accidentally requesting amounts larger than allocatable by a node and sets limits for VPAs to scale to.
> set default max resources in limit ranges

- modules/common/namespace/variables.tf
Change max mem limit range format to Mi instead of Gi so terraform doesn't try to reformat it
> change limit range max mem from Gi to Mi

- modules/common/istio/charts/jaeger/.helmignore
- modules/common/istio/charts/jaeger/Chart.yaml
- modules/common/istio/charts/jaeger/templates/_affinity.tpl
- modules/common/istio/charts/jaeger/templates/_helpers.tpl
- modules/common/istio/charts/jaeger/templates/deployment-jaeger.yaml
- modules/common/istio/charts/jaeger/templates/ingress.yaml
- modules/common/istio/charts/jaeger/templates/pvc.yaml
- modules/common/istio/charts/jaeger/templates/service-jaeger.yaml
- modules/common/istio/charts/jaeger/templates/service.yaml
- modules/common/istio/charts/jaeger/templates/statefulset.yaml
- modules/common/istio/charts/jaeger/values.yaml
- modules/common/istio/istio-values.tpl
- modules/common/istio/jaeger-values.tpl
- modules/common/istio/main.tf
We moved the istio jaeger subchart into the istio terraform module so that we could change the size of the persistent storage. It's not super clean but it is meant to be a short term fix until we can move the the standalone jaeger chart and implement storage using elasticsearch or casandra.
> move jaeger from istio helm chart into local helm chart

- modules/lead/toolchain/kube-resource-report-values.tpl
Fixes spacing on kube-resource-report-values.tpl
Increases update interval for cluster data to 5 minutes. (Default was 1 minute) Less frequent updates should only minority hurt usability, but should significantly reduce cpu load and throttling.
> Lower refresh rate for kube-resource-report

- modules/environment/aws/eks/iam.tf
- stacks/environment-aws/iam.tf
Allows lead_operator_slack_service_account role to create codecommit repositores and allows lead_workspace_role to push to codecommit repositories
> Add rules to policies for sparky import

- Makefile
- modules/lead/toolchain/keycloak.tf
- modules/lead/toolchain/variables.tf
- stacks/environment-aws/lead.tf
- stacks/environment-aws/variables.tf
when `enable_google_login` is true, google authentication will be added to the toolchain realm (used to be done in prod manually)
when `enable_test_user` is true, a test user named `casey` will be created in the toolchain realm (used to be done in sandbox manually)
> terraform configuration for google login via keycloak & keycloak test user

- .editorconfig
- modules/tools/vault/charts/vault-helm/.helmignore
- modules/tools/vault/charts/vault-helm/Chart.yaml
- modules/tools/vault/charts/vault-helm/README.md
- modules/tools/vault/charts/vault-helm/templates/NOTES.txt
- modules/tools/vault/charts/vault-helm/templates/_helpers.tpl
- modules/tools/vault/charts/vault-helm/templates/injector-clusterrole.yaml
- modules/tools/vault/charts/vault-helm/templates/injector-clusterrolebinding.yaml
- modules/tools/vault/charts/vault-helm/templates/injector-deployment.yaml
- modules/tools/vault/charts/vault-helm/templates/injector-mutating-webhook.yaml
- modules/tools/vault/charts/vault-helm/templates/injector-service.yaml
- modules/tools/vault/charts/vault-helm/templates/injector-serviceaccount.yaml
- modules/tools/vault/charts/vault-helm/templates/server-clusterrolebinding.yaml
- modules/tools/vault/charts/vault-helm/templates/server-config-configmap.yaml
- modules/tools/vault/charts/vault-helm/templates/server-discovery-role.yaml
- modules/tools/vault/charts/vault-helm/templates/server-discovery-rolebinding.yaml
- modules/tools/vault/charts/vault-helm/templates/server-disruptionbudget.yaml
- modules/tools/vault/charts/vault-helm/templates/server-ha-active-service.yaml
- modules/tools/vault/charts/vault-helm/templates/server-ha-standby-service.yaml
- modules/tools/vault/charts/vault-helm/templates/server-headless-service.yaml
- modules/tools/vault/charts/vault-helm/templates/server-ingress.yaml
- modules/tools/vault/charts/vault-helm/templates/server-service.yaml
- modules/tools/vault/charts/vault-helm/templates/server-serviceaccount.yaml
- modules/tools/vault/charts/vault-helm/templates/server-statefulset.yaml
- modules/tools/vault/charts/vault-helm/templates/ui-service.yaml
- modules/tools/vault/charts/vault-helm/values.yaml
- modules/tools/vault/main.tf
- modules/tools/vault/values.tpl
- modules/tools/vault/variables.tf
- modules/tools/vault/vault-config.hcl.tpl
don't bother reviewing the contents of `modules/tools/vault/charts/vault-helm`, as that is a direct copy/paste from https://github.com/hashicorp/vault-helm.  it was copy/pasted because this chart is not hosted on a registry
I have not tested this yet on a cluster.
> add vault module to be consumed by shared service stack

- modules/common/istio/istio-values.tpl
- modules/lead/toolchain/prometheus-values.tpl
- remove prometheus scrap annotation (only used by istio promethesu) from kube state metrics and node explorer
- adjust prometheus resources
> Eng 1795 tune prometheus

- modules/common/istio/variables.tf
- modules/environment/aws/eks/main.tf
- modules/environment/aws/eks/variables.tf
- stacks/environment-aws/elasticsearch.tf
- bump elasticsearch disk size
- reduce sampling rate for traces
- decrease EKS worker node root disk size from 100G to 50G
> misc fixes related to jaeger tracing

- stacks/apps/sharedsvc/outputs.tf
- stacks/apps/sharedsvc/vault.tf
- stacks/config/sharedsvc/main.tf
- stacks/config/sharedsvc/variables.tf
this can be applied after running `vault login` and using `terragrunt apply-all` from `lead-environments/aws/liatrio-sharedsvc`
> initial example vault config

- modules/tools/cluster-autoscaler/cluster-autoscaler-values.tpl
- modules/tools/elasticsearch/elasticsearch-values.tpl
- increate es mem request. es will eat up as much memory as it can get it hands on so makes sense to have request closer to limit
- disable skip nodes with local storage. the autoscaler enables this by default which limits how much the cluster can scale down. if we cared about what was being stored by the pod it should have a pvc anyway.
> Post lab updates

- modules/lead/toolchain/kube-resource-report.tf
- stacks/environment-aws/lead.tf
- stacks/environment-local/lead.tf
This PR relocates the existing `kube-resource-report` module from the `toolchain` module to its own module under `module/tools`. Corresponding updates have been made to both the `local` and `environment-aws` stacks.
> Relocated kube-resource-report module to tools/

- modules/lead/toolchain/harbor.tf
- modules/lead/toolchain/keycloak.tf
- modules/lead/toolchain/outputs.tf
- modules/lead/toolchain/variables.tf
- modules/lead/toolchain/versions.tf
- modules/tools/kibana/versions.tf
- stacks/environment-aws/lead.tf
- stacks/environment-aws/main.tf
- stacks/environment-aws/versions.tf
This PR updates the required_providers config to point to the newly published `harbor` and `keycloak` providers.
> Updated harbor and keycloak provider config to point to Terraform registry

- stages/cloud-provider/aws/lead/eks.tf
This PR fixes the missing `cluster_variable` version in `stages/lead/eks.tf`
> Added missing cluster_version

- modules/lead/product-jenkins/keycloak.tf
As part of https://github.com/liatrio/lead-terraform/commit/7c85d0e3909bd82d394d47d4f0b2b507830d3838#diff-5180734303cdbe1d5e9ffd88b33501c4 we renamed the metadata for the keycloak_admin kubernetes secret to "keycloak_credentials" and updated the metadata. Updating the product-jenkins keylcloak module to use the appropriate secret name and values.
> Use updated k8s secret name for keycloak

- modules/lead/product-base/mongo.tpl
without this change, there's a small chance that the mongodb pod is not actually ready for authentication attempts by the time that the helm chart finishes deploying, causing an issue with the terraform code that sets up a connection between vault and mongodb.
> increase success threshold for mongodb liveness and readiness probes

- stacks/product-test/main.tf
this isn't a super important change since this stack is only used to test the product operator, but there were some changes to the base product that this relied on that made local testing difficult, so I cleaned this up a bit.
> update the product-test stack for testing the product operator

- modules/lead/product-jenkins/pod-templates.tpl
accidentally left this in when I copy and pasted the the maven template but that secret doesn't exist after artifactory was removed so the maven template was probably broken also.
> remove maven secret volume

- modules/tools/lab-partner/main.tf
- modules/tools/lab-partner/variables.tf
- stages/apps/lead/lab_partner.tf
I noticed that we still aren't actually using `count` on modules, even though that was pretty much the main goal of the refactoring work we did.  this one in particular was making it difficult to stand up the lab environment, but we should come back to all of the other feature flags and do something similar.
> better feature flag for lab-partner

- modules/tools/vault-less-secure/main.tf
this should prevent cases where the vault root token stored in a k8s secret is replaced with an empty string because the shell script resource is recreated, tries to unlock vault again and returns an error.
> prevent vault root token change

- stages/cloud-provider/aws/lead/main.tf
Reverts liatrio/lead-terraform#436
turns out this is actually needed within the `eks` module.  my bad
> Revert "remove k8s provider in cloud-provider tf stage"

- modules/lead/product-jenkins/versions.tf
- stacks/product-jenkins/versions.tf
- stages/cloud-provider/aws/lead/iam.tf
Updated the version of Terraform that product-jenkins was using from 12 to 13 and then to 14, expanded the IAM role permissions for the S3 bucket to compensate for the update. Listed the providers in required_providers section inside the versions.tf file as required by the Terraform 13 update.
> Terraform 14 upgrade

- modules/lead/app-ingress/README.md
- modules/lead/app-ingress/main.tf
- modules/lead/app-ingress/variables.tf
- stages/apps/lead/nginx.tf
if istio is disabled, this will allow applications to still be exposed via `Ingress` instead of using a `VirtualService` / `Gateway`
> deploy ingress controllers for app traffic

- modules/tools/cert-manager/main.tf
this change was already made but must of gotten lost when we updated the k8s version
> upgrade cert manager chart version to 1.2.0

- modules/common/nginx-ingress/main.tf
- modules/common/nginx-ingress/nginx-ingress-values.tpl
- modules/common/nginx-ingress/variables.tf
- modules/lead/toolchain-ingress/main.tf
I ended up using the `downscaler/downtime-replicas` annotation so we'd just have one replica for the controller running off-hours.
> avoid downscaling internal ingress

- modules/tools/docker-registry/values.yaml.tpl
I saw a lot of throttling when testing this with a few different images
> bump CPU limits for docker registry pods

- modules/environment/aws/eks/main.tf
- modules/environment/aws/iam/external-dns/main.tf
- modules/environment/aws/iam/external-dns/variables.tf
- modules/tools/external-dns/main.tf
- modules/tools/external-dns/values.tpl
- modules/tools/external-dns/variables.tf
- stages/apps/sharedsvc/infrastructure.tf
- stages/apps/sharedsvc/issuers.tf
- stages/apps/sharedsvc/main.tf
- stages/apps/sharedsvc/nginx.tf
- stages/apps/sharedsvc/sonarqube.tf
- stages/apps/sharedsvc/variables.tf
- stages/cloud-provider/aws/sharedsvc/iam.tf
- stages/cloud-provider/aws/sharedsvc/outputs.tf
- stages/config/sharedsvc/vault.tf
* Adds sonarqube deployment to shared services cluster
* Handles some errors from the latest AMI version used by the cluster
* Adds an additional external-dns release to handle the public zone
* Adds external-facing ingress components
* Upgrades the external-dns release to the latest version
> Adding sonarqube to shared services

- modules/lead/product-jenkins/controller.tpl
- modules/lead/product-jenkins/github.tf
- modules/lead/product-jenkins/jenkins-env.tpl
- modules/lead/product-jenkins/jenkins-values.tpl
- modules/lead/product-jenkins/main.tf
- modules/lead/product-jenkins/master-node.tpl
- modules/lead/product-jenkins/pipelines-git.tpl
- modules/lead/product-jenkins/pod-templates.tpl
- modules/lead/product-jenkins/security-config.tpl
- modules/lead/product-jenkins/slack-config.tpl
- modules/lead/product-jenkins/toolchain.tf
this PR upgrades the jenkins chart helm chart within the jenkins product to the latest version, and fixes a potential issue with downloading large git repositories by performing a shallow clone.
the contents of this PR should be used with https://github.com/liatrio/builder-images/pull/77
> chore: upgrade jenkins chart, fix issues with cloning large repositories

- modules/config/harbor/main.tf
- modules/config/harbor/variables.tf
- modules/tools/rode/harbor-collector-values.yaml.tpl
- modules/tools/rode/main.tf
- modules/tools/rode/variables.tf
- stages/apps/sharedsvc/harbor.tf
- stages/apps/sharedsvc/outputs.tf
- stages/apps/sharedsvc/rode.tf
- stages/config/sharedsvc/harbor.tf
- stages/config/sharedsvc/variables.tf
It's worth mentioning that this isn't the latest and greatest version of the collector, instead it's a patch version behind so that it's compatible with the version of Harbor that's in use. See https://github.com/rode/collector-harbor/pull/19 for more details. 
If we upgrade Harbor, we'll need to bump the collector as well.
> Deploy Harbor collector

- stages/vault/sharedsvc/vault.tf
also set the max token ttl to thirty minutes
I already applied this change so I can continue with setting up the nonprod environment
> allow non-prod admin to use vault

- modules/tools/github-actions-runners/main.tf
- stages/apps/sharedsvc/kube-prometheus-stack.tf
- stages/apps/sharedsvc/main.tf
I can't run plan/apply on sharedsvc against master without these changes.
> fix: update usage of kube-prometheus-stack module in sharedsvc to include new required arguments

- modules/tools/kube-prometheus-stack/values.tpl
- Silencing target down alert because of an issue with aws: [](https://github.com/aws/containers-roadmap/issues/657)
> Silence alert down alert

- stages/vcluster/aws.tf
- stages/vcluster/host_cluster.tf
- stages/vcluster/versions.tf
- stages/vcluster/virtual_cluster.tf
I really hope this doesn't take as long when running in CI compared to locally
> fix: wait as long as it takes for the vcluster to be online and reachable

- stages/apps/lead/vcluster.tf
- stages/cloud-provider/aws/lead/iam.tf
- stages/cloud-provider/aws/lead/route53.tf
- stages/cloud-provider/aws/lead/variables.tf
the DNS / route53 changes are here in order to reduce the amount of time it takes for new DNS records to propagate to the VPC resolvers.  the significant portion here is the `SOA` record, which will have a reduced TTL compared to the one that route53 creates for you.
I also added a wildcard cert that can be used by applications running on a vcluster, and hooked it up to the vcluster ingress controller that was already in place.
> feat: move vcluster DNS records to their own route53 zone, add wildcard cert for vcluster apps

- stages/apps/lead/issuer.tf
- stages/apps/lead/variables.tf
- stages/apps/lead/vcluster.tf
- stages/cloud-provider/aws/lead/outputs.tf
I'm _reasonably_ sure this works, but let's encrypt is currently experiencing an outage so I haven't been able to test it yet.
> fix: create dedicated cert-manager issuer for new vcluster zone

- modules/tools/kibana/main.tf
- update helm chart from v7.6.2 to v7.7.0 to allow redirection on the readinessProbe to fix 302 status code error
- [release 7.7.0](https://github.com/elastic/helm-charts/releases/tag/7.7.0)
> fix: update kibana helm chart

- .github/workflows/test.yml
- modules/environment/aws/eks/main.tf
This adds the roles to the `aws-auth` `ConfigMap` resource and therefore allows `Developer` and other assumed roles to interact with the cluster.
> fix(eks): fix vcluster workflow by setting manage_aws_auth_configmap to true in EKS module  

- modules/tools/elasticsearch/elasticsearch-curator-values.tpl
We want to include a filter on the delete old indices action that excludes the github actions metrics indices. We want to exclude these repos because we want historical data.
> fix: add exclusion on elasticsearch-curtor-values.tpl

- .github/workflows/terraform-validate.yml
This PR changes the codeql-workflow so that when we run tfsec we will upload the results of the scan to GitHub's security tab. This is a refactor from before in which reviewdog would add comments to one's PR that introduced new tfsec alerts.
> ci: refactor tfsec workflow

- stages/apps/lead/github-runners.tf
FLY-85
Each statement was failing to iterate through the list when set to reference by value.  This was resulting in the existing namespaces being set to destroy and never creating the new ones added.  Adjusted the each to iterate through keys and it now works as expected.
> fix:  modified each statement for namespace
