.gitignore
modules/common/namespace/main.tf
modules/lead/toolchain/artifactory.tf
modules/lead/toolchain/variables.tf
stacks/environment-aws/lead.tf
stacks/environment-aws/variables.tf
stacks/environment-local/lead.tf
stacks/environment-local/main.tf
stacks/environment-local/variables.tf

Artifactory with license and admin pw set via tf.

Artifactory toolchain

---

local/minikube/tiller.tf

Terraform to configure the necessary kubernetes resources for tiller to interact with the lead toolchain.

Kubernetes resources for tiller

---

modules/common/namespace/issuer.tf
modules/lead/infrastructure/certmanager.tf

Use relative paths for local helm charts

Local helm chart

---

modules/lead/toolchain/sonarqube.tf

Adding sonarqube

---

modules/lead/dashboard/main.tf
modules/lead/dashboard/variables.tf
stacks/environment-aws/lead.tf
stacks/environment-aws/variables.tf
stacks/environment-local/variables.tf

Comments out Logstash variables for plugins which are currently deemed unnecessary.

Disable Logstash Plugins

---

modules/lead/sdm/main.tf
modules/lead/sdm/operator-toolchain-values.tpl
modules/lead/sdm/variables.tf
stacks/environment-aws/eks.tf
stacks/environment-aws/lead.tf

for handling federation to AWS Cloud9 from slack

create new IAM role for SDM to use

---

modules/common/cert-issuer/issuer-values.tpl
modules/common/cert-issuer/main.tf
modules/common/cert-issuer/variables.tf
modules/common/istio/main.tf
modules/common/istio/variables.tf
modules/lead/infrastructure/main.tf
modules/lead/infrastructure/variables.tf
modules/lead/product/production.tf
modules/lead/product/staging.tf
modules/lead/product/toolchain.tf
modules/lead/product/variables.tf
modules/lead/sdm/main.tf
modules/lead/sdm/operator-toolchain-values.tpl
modules/lead/sdm/variables.tf
modules/lead/toolchain/main.tf
modules/lead/toolchain/variables.tf
stacks/environment-aws/istio.tf
stacks/environment-aws/lead.tf
stacks/environment-aws/variables.tf
stacks/product-aws/main.tf
stacks/product-aws/variables.tf

- turn on http provider for istio cert issuer
- set cert issuer server as tf var so we can change to staging per environment

Istio cert

---

modules/lead/sdm/operator-toolchain-values.tpl

lets encrypt staging

---

local/product/terragrunt.hcl

Pointing local/product configuration at stack/product-local

Fixed local/product configuration

---

modules/common/ca-issuer/README.md
modules/common/ca-issuer/main.tf
modules/common/ca-issuer/outputs.tf
modules/common/ca-issuer/variables.tf
modules/common/ca-issuer/versions.tf
modules/common/cert-issuer/helm/cert-manager-issuers/templates/issuer.yaml
modules/common/cert-issuer/helm/cert-manager-issuers/values.yaml
modules/common/cert-issuer/issuer-values.tpl
modules/common/cert-issuer/main.tf
modules/common/cert-issuer/variables.tf
modules/common/certificates/certificate-values.tpl
modules/common/certificates/helm/certificates/templates/certificates.yaml
modules/common/certificates/helm/certificates/values.yaml
modules/common/certificates/main.tf
modules/common/certificates/variables.tf
modules/lead/toolchain/main.tf

- add module to create a ca issuer
- create sample issuer and cert in toolchain

Eng 1256 - CA issuer

---

modules/lead/toolchain/grafeas.tf

grafeas chart path fix

---

modules/common/certificates/helm/certificates/templates/certificates.yaml
modules/common/certificates/helm/certificates/templates/role.yaml
modules/common/certificates/helm/certificates/templates/rolebinding.yaml
modules/common/certificates/helm/certificates/templates/serviceaccount.yaml
modules/common/certificates/helm/certificates/values.yaml

Create service account to allow secret validator to get secrets.

Grafeas rbac

---

modules/lead/toolchain/grafeas.tf

Fix path to grafeas helm chart

---

modules/common/certificates/certificate-values.tpl
modules/common/certificates/helm/certificates/templates/certificates.yaml
modules/common/certificates/helm/certificates/values.yaml
modules/common/certificates/main.tf
modules/common/certificates/variables.tf
modules/lead/toolchain/grafeas.tf

Set boolean to wait for cert secret verification

Wait for cert

---

modules/lead/toolchain/charts/kritis-chart/templates/kritis-server-deployment.yaml
modules/lead/toolchain/charts/kritis-chart/templates/validating-webhook-config.yaml
modules/lead/toolchain/grafeas.tf

Fixes typo in webhook name + updates certificate for grafeas to have grafeas-server dns name

Grafeas tls

---

modules/common/nginx-ingress/main.tf

Make sure ingress rbac has been created before running ingress helm chart

add nginx ingress deps

---

stacks/environment-aws/lead.tf

Removing erroneous var from toolchain. It is already being passed into sdm

Removing erroneous var

---

modules/lead/product/jenkins-values.tpl

Mount volume for artifactory creds for maven agent

Mount volume for artifactory creds for maven agent

---

modules/lead/product/jenkins-values.tpl

Increase maven pod memory requests and limits

Increase maven pod memory requests and limits

---

modules/common/aws-ses-smtp/main.tf
modules/common/ca-issuer/main.tf
modules/common/istio/main.tf
modules/common/namespace/variables.tf
modules/common/nginx-ingress/main.tf
modules/lead/infrastructure/variables.tf
modules/lead/sdm/variables.tf
modules/lead/toolchain/kritis.tf
stacks/environment-aws/istio.tf
stacks/environment-aws/ses.tf

clean up code that causes deprecated warnings with terraform 0.12.17

fix warnings

---

modules/common/flagger/helm/flagger-crds/Chart.yaml
modules/common/flagger/helm/flagger-crds/templates/crds.yaml
modules/common/flagger/main.tf

* Upgrades flagger to 0.20.4
* Adds toggle to terraform for flagger CRD creation

Upgrade flagger

---

.gitignore
modules/common/certificates/outputs.tf
modules/common/istio-ingress/helm/istio-ingress/Chart.yaml
modules/common/istio-ingress/helm/istio-ingress/templates/istio.yaml
modules/common/istio-ingress/helm/istio-ingress/values.yaml
modules/common/istio-ingress/istio-ingress-values.tpl
modules/common/istio-ingress/main.tf
modules/common/istio-ingress/variables.tf
modules/lead/toolchain/artifactory.tf
modules/lead/toolchain/main.tf
modules/lead/toolchain/prometheus.tf
modules/lead/toolchain/variables.tf
stacks/environment-aws/lead.tf
stacks/environment-aws/main.tf
stacks/environment-local/istio.tf
stacks/environment-local/lead.tf

Add Istio ingress for new Grafana

ENG-1396 istio ingress

---

.gitignore
modules/lead/toolchain/prometheus-values.tpl

group alerts by namespace/pod
only alert on toolchain, lead-system and istio-system namespaces
filter out alerts trying to monitor control plain

tune monitoring alerts

---

.gitignore
Brewfile
README.md

- Formatted Brewfile based on Ruby conventions (it's a ruby file)
- Added `secrets` directory while still ignoring files provided by user
- Added `terragrunt validate` step to save users from failing `apply` as often
- Added additional variables now required for `.tfvars` files

ENG-1423 - Improving README.md

---

modules/lead/infrastructure/downscaler.tf
modules/lead/infrastructure/k8s-spot-termination-handler.tf
modules/lead/infrastructure/variables.tf
stacks/environment-aws/lead.tf
stacks/environment-local/lead.tf

these aren't needed when running locally

add feature flags for downscaler and spot termination handler

---

modules/lead/product/jenkins-values.tpl

add goreleaser build agent to jenkins CASC

Eng 1443 gittyup jenkins pipeline

---

local/environment/terragrunt.hcl
stacks/environment-local/issuer.tf
stacks/environment-local/istio.tf
stacks/environment-local/lead.tf

Probably not perfect but this was enough for me to be able to run terraform apply locally

Update local dev cert issuer

---

modules/lead/dashboard/dashboard-values.tpl
modules/lead/dashboard/main.tf
modules/lead/dashboard/variables.tf
stacks/environment-aws/lead.tf
stacks/environment-aws/variables.tf

add value to set replica count of elasticsearch in dashboard module

---

modules/common/istio/charts/jaeger/templates/statefulset.yaml
modules/common/istio/jaeger-values.tpl

increase readiness threshold for jaeger

increase readiness/liveness threshold

---

modules/lead/product/harbor.tf
stacks/product-aws/main.tf

Add missing enable_artifactory variable when calling product module

Config fix

---

stacks/product-aws/variables.tf

add back necessary vars to product-aws stack

add back necessary vars to product-aws stack

---

modules/lead/product-jenkins/toolchain.tf

Give jenkins serviceaccount ability to manage builds.sdm.liatr.io

add sdm.liatr.io to jenkins role

---

stacks/environment-aws/main.tf
stacks/environment-local/main.tf
stacks/product-aws/main.tf
stacks/product-jenkins/main.tf
stacks/product-local/main.tf
stacks/product-test/main.tf
tests/testdata/common/cert-issuer/main.tf
tests/testdata/lead/dashboard/main.tf
tests/testdata/lead/toolchain-ingress/main.tf
tests/testdata/tools/cert-manager/main.tf
tests/testdata/tools/kube-resource-report/main.tf
tests/testdata/tools/sdm/main.tf

fix bug that changes relative helm charts on every apply

helm provider -> 1.1.1

---

modules/lead/product-base/production.tf
modules/lead/product-base/staging.tf
modules/lead/product-jenkins/harbor.tf

change robot_account_access to access to account for updates to the harbor provider

change robot_account_access to access

---

modules/environment/aws/eks/iam.tf
stacks/environment-aws/iam.tf

policy permissions for operator-slack to create ECR repos on @sparky add

policy permissions for operator-slack to create ECR repos on @sparky add

---

modules/lead/product-jenkins/security-config.tpl
modules/lead/product-jenkins/toolchain.tf
modules/lead/sdm/operator-toolchain-values.tpl

Make jenkins admin password creation sensitive. Pass cluster_domain as env var to operator-slack.

Eng 1745 && ENG-1746 && ENG-1747

---

stacks/environment-aws/iam.tf

give operator slack service account permissions to get codecommit metadata

give operator slack service account permissions to get codecommit metadata

---

modules/environment/aws/code-services/main.tf
modules/environment/aws/code-services/outputs.tf
modules/environment/aws/code-services/variables.tf
modules/environment/aws/eks/output.tf
modules/lead/product-aws/aws.tf
modules/lead/product-aws/variables.tf
modules/lead/sdm/main.tf
modules/lead/sdm/operator-toolchain-values.tpl
stacks/environment-aws/codeservices.tf
stacks/environment-aws/iam.tf
stacks/environment-aws/lead.tf
stacks/product-aws/main.tf
stacks/product-aws/variables.tf

this will allow deployments to access the EKS cluster

create codebuild project in lead VPC

---

modules/lead/product-base/production.tf
modules/lead/product-base/staging.tf

trim rbac for ci role

---

modules/tools/kube-janitor/main.tf

this fixes the issue with failed jobs not being cleaned up

kube-janitor image version v0.2.1

---

modules/lead/product-base/helm/product-init/Chart.yaml
modules/lead/product-base/helm/product-init/templates/configmap.yaml
modules/lead/product-base/production.tf
modules/lead/product-base/staging.tf

no longer needed because tiller is gone

remove product init chart from product-base tf module

---

modules/tools/k8s-spot-termination-handler/values.yaml

- Increase CPU limit to reduce throttling
- Decrease Memory request and limit

reduce spot termination handler memory and increase cpu limit

---

stacks/environment-aws/iam.tf

without this change, the product operator service account has no AWS permissions at all when the AWS lab is disabled

split product operator IAM into separate policies for AWS lab

---

modules/lead/sdm/operator-toolchain-values.tpl

set env for image to use for jobs created by `sparky support`

add support image env var for slack operator

---

modules/lead/sdm/operator-toolchain-values.tpl

fix tag for support image

---

modules/tools/kibana/charts/gatekeeper/.helmignore
modules/tools/kibana/charts/gatekeeper/Chart.yaml
modules/tools/kibana/charts/gatekeeper/values.yaml

forgot to add these in my last PR, oops

add missing gatekeeper chart config

---

stacks/environment-aws/iam.tf

need for @sparky workspace share

add c9 create environment membership permission to slack operator policy

---

modules/environment/aws/eks/main.tf
modules/environment/aws/eks/variables.tf
modules/tools/vault/main.tf
modules/tools/vault/values.tpl
stacks/cluster/eks-minimal/eks.tf
stacks/cluster/eks-minimal/variables.tf
stacks/config/sharedsvc/main.tf
stacks/config/sharedsvc/variables.tf
stacks/config/sharedsvc/vault-admin.tf
stacks/config/sharedsvc/vault-lead.tf
stacks/config/sharedsvc/vault-policies/lead-aws-admin.hcl
stacks/config/sharedsvc/vault-policies/lead-aws-developer.hcl
stacks/config/sharedsvc/vault-policies/vault-admin.hcl
stacks/config/sharedsvc/vault.tf

- add ability to pass additional mapped roles for eks clusters
- pin vault version
- add missing iam permissions for vault server
- secret engine for lead-terraform
- aws authentication and policies for lead-terraform based on administrator and developer roles
- aws authentication and policies for vault administration

initial vault configuration

---

stacks/environment-azure/main.tf

Created environment_azure dir
Created main.tf, output.tf and variables.tf

Fixes #362 create azure directory and initial tf files

---

stacks/environment-azure/main.tf

Merge intial azure setup into master.  Hail the short-lived branches!

Fix #364 create azure directory and initial tf files (#363)

---

environments/azure/sandbox/cloudprovider/terragrunt.hcl
stacks/environment-azure/main.tf
stacks/environment-azure/variables.tf

Terraform and terragrunt for azurerm resources

closes #368 Vm from terraform

---

stages/apps/lead/harbor.tf

This PR fixes incorrect cluster variable name

Update incorrect cluster variable name

---

modules/tools/harbor/main.tf

Fix for deprecated `crd_waiter` variable

Removed depreceated crd_waiter variable

---

stages/apps/lead/infrastructure.tf

PR fixes incorrect variable value

Updated clusterautoscaler arn

---

stages/apps/lead/variables.tf
stages/cloud-provider/aws/lead/outputs.tf

Added input variable for cluster_autoscaler

---

stages/config/lead/variables.tf

Fix missing enable_harbor variable

Added enable_harbor variable to config stage

---

Makefile
modules/tools/k8s-spot-termination-handler/main.tf
modules/tools/keycloak/main.tf
modules/tools/keycloak/outputs.tf
modules/tools/keycloak/values.tpl
modules/tools/metrics-server/main.tf
modules/tools/sonarqube/sonarqube-values.tpl
tests/aws/eks_test.go
tests/common/cert-manager.go
tests/common/versions.go
tests/local/local_test.go
tests/testdata/common/cert-issuer/main.tf
tests/testdata/common/cert-issuer/variables.tf
tests/testdata/lead/toolchain-ingress/main.tf
tests/testdata/lead/toolchain-ingress/variables.tf
tests/testdata/tools/harbor/main.tf

Update several module version to work with k8s 1.16
Fix misc test problems from recent module changes

ENG-1912-modules+k8s1.16

---

modules/lead/product-jenkins/toolchain.tf
stacks/product-jenkins/main.tf
stacks/product-jenkins/variables.tf
stacks/product-jenkins/versions.tf

- Config context default to null
- Pinning version of Kubernetes to 2.0.1
- Updated helm chart repo for Jenkins

Updating Jenkins provider 

---

modules/tools/mattermost/charts/mattermost-team-edition/.helmignore
modules/tools/mattermost/charts/mattermost-team-edition/Chart.yaml
modules/tools/mattermost/charts/mattermost-team-edition/OWNERS
modules/tools/mattermost/charts/mattermost-team-edition/README.md
modules/tools/mattermost/charts/mattermost-team-edition/requirements.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/NOTES.txt
modules/tools/mattermost/charts/mattermost-team-edition/templates/_deprecations.tpl
modules/tools/mattermost/charts/mattermost-team-edition/templates/_helpers.tpl
modules/tools/mattermost/charts/mattermost-team-edition/templates/_warnings.tpl
modules/tools/mattermost/charts/mattermost-team-edition/templates/deployment.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/ingress.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/pvc-config.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/pvc-plugins.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/pvc.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/route.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/secret-config.yaml
modules/tools/mattermost/charts/mattermost-team-edition/templates/service.yaml
modules/tools/mattermost/charts/mattermost-team-edition/values.yaml
modules/tools/mattermost/main.tf
modules/tools/mattermost/values.yaml.tpl
modules/tools/mattermost/variables.tf
stages/apps/lead/mattermost.tf
stages/apps/lead/variables.tf

ignore the vendored chart if you can.  we can remove that once these two PRs are merged:
- https://github.com/mattermost/mattermost-helm/pull/208
- https://github.com/mattermost/mattermost-helm/pull/209

add mattermost

---

modules/common/nginx-ingress/main.tf
modules/tools/elasticsearch/main.tf
modules/tools/fluent-bit/main.tf
modules/tools/prometheus-operator/main.tf

https://helm.sh/blog/new-location-stable-incubator-charts/
I've already done the state surgery in sandbox.  haven't done it in prod yet.  we'll want to do that before any further applies so releases don't get removed and recreated

migrate to new stable chart location

---

modules/environment/aws/eks/main.tf
modules/environment/aws/eks/variables.tf
stages/cloud-provider/aws/lead/eks.tf
stages/cloud-provider/aws/lead/variables.tf

configure nodes docker daemon to use registry mirror via ec2 instance user data

docker registry mirror

---

modules/common/nginx-ingress/nginx-ingress-values.tpl
stages/apps/lead/toolchain.tf

- bump up ingress backend cpu resources
- add ns dependency to toolchain ingress

Ingress resources

---

modules/config/harbor/charts/harbor-config/Chart.yaml
modules/config/harbor/charts/harbor-config/files/config.sh

Updated the path for the OIDC script to include v2.0 in order to work with the Harbor 2.0 update.

Oidc script update

---

.gitignore
Jenkinsfile
Makefile
stacks/environment-local/Makefile
stacks/product-aws/Makefile
stacks/product-aws/main.tf
stacks/product-aws/versions.tf
stacks/product-jenkins/Makefile
stacks/product-local/Makefile
stacks/product-local/versions.tf
stacks/product-test/Makefile
stacks/product-test/main.tf
stacks/product-test/versions.tf
stages/apps/azure-example/Makefile
stages/apps/azure-example/main.tf
stages/apps/azure-example/versions.tf
stages/apps/lead/Makefile
stages/apps/lead/main.tf
stages/apps/sharedsvc/Makefile
stages/cloud-provider/aws/lead/Makefile
stages/cloud-provider/aws/sharedsvc/Makefile
stages/cloud-provider/azure/lead/Makefile
stages/config/lead/Makefile
stages/config/lead/main.tf
stages/config/lead/versions.tf
stages/config/sharedsvc/Makefile

update the terraform validate make target to fix pipeline errors

update terraform validate 

---

modules/common/nginx-ingress/main.tf
modules/common/nginx-ingress/nginx-ingress-values.tpl
modules/common/nginx-ingress/variables.tf
modules/lead/toolchain-ingress/README.md
modules/lead/toolchain-ingress/main.tf

This creates an nginx-ingress-controller to handle ingresses that are specifically accessible by the internal VPN.

Add internal ingress

---

modules/tools/github-actions-runners/github-actions-runners/Chart.yaml
modules/tools/github-actions-runners/github-actions-runners/templates/clusterrole.yaml

for rode demo deployment.  already applied these changes in prod to unblock the demo pipeline.

allow github actions runners to manage extensions.ingress, batch.jobs

---

modules/lead/product-base/production.tf
modules/lead/product-base/staging.tf

Added this for the envelope game pipeline to be able to create an ingress for envelopegame.com

fix: add rbac for Jenkins to manage certificates

---

modules/tools/github-actions-runners/github-actions-runners/Chart.yaml
modules/tools/github-actions-runners/github-actions-runners/templates/clusterrole.yaml

should resolve failures such as https://github.com/rode/demo/runs/2784489085

allow github actions runner to work with PVCs

---

modules/environment/aws/github-runners-s3/main.tf
modules/tools/vault-less-secure/main.tf
stages/apps/lead/vault.tf
stages/apps/sharedsvc/github-runners.tf
stages/apps/sharedsvc/variables.tf
stages/cloud-provider/aws/lead/vault.tf
stages/cloud-provider/aws/sharedsvc/github-runners-s3.tf
stages/cloud-provider/aws/sharedsvc/outputs.tf
stages/cloud-provider/aws/sharedsvc/variables.tf

* copies github runner configuration from lead to shared services

Github runners in shared services

---

modules/tools/rode/main.tf
modules/tools/rode/tfsec-collector-values.yaml.tpl
modules/tools/rode/variables.tf
stages/apps/sharedsvc/rode.tf

~I haven't applied this yet, but wanted to open this before I did.~ I've already applied these changes. 
Also includes a few other changes:
- excludes Rode namespace from downscaling
- force SSL redirects on all ingress
- fixes the Rode UI count

Include tfsec collector in Rode install

---

stages/apps/lead/outputs.tf

- updated ignite lab vault secrets to include github token and username

fix: update keycloak_hostname in output.tf

---

stages/cloud-provider/aws/sharedsvc/eks.tf
stages/cloud-provider/aws/sharedsvc/github-runners-s3.tf
stages/cloud-provider/aws/sharedsvc/iam.tf
stages/cloud-provider/aws/sharedsvc/outputs.tf

I had to apply these changes for the managed node group updates for the shared svc cluster

fix: update new outputs for eks module

---

modules/tools/rode/image-scanner-collector-values.yaml.tpl
modules/tools/rode/main.tf
modules/tools/rode/variables.tf
stages/apps/lead/kube-prometheus-stack.tf
stages/apps/sharedsvc/rode.tf

* adds a docker config secret
* adds a helm release for the image scanner collector

Image scanner collector

---

modules/tools/rode/main.tf

Rode UI:
- fixes a bug with the playground
Image scanner collector:
- better validation on the image name
- report failed scans to Rode

Update Rode components

---

modules/tools/kube-prometheus-stack/values.tpl

- Add button to silence alerts in alertmanager from slack.

Slack Silence alert button

---

modules/tools/kube-prometheus-stack/values.tpl

Reverts liatrio/lead-terraform#522

chore: revert pr "Silence alert down alert"

---

stages/vcluster/outputs.tf

this just helps the pipeline avoid hardcoding variables

feat: add extra outputs for vcluster module

---

stages/apps/lead/variables.tf

fix: disable lab partner

---

stages/cloud-provider/aws/sharedsvc/eks.tf
stages/cloud-provider/aws/sharedsvc/variables.tf

this will allow us to set the coredns version from lead-environments

feat: support cluster addons for shared-svc cluster

---

modules/common/cert-issuer/main.tf
modules/common/certificates/main.tf
modules/common/flagger/main.tf
modules/common/opa/main.tf
modules/config/harbor/versions.tf
modules/config/keycloak/versions.tf
modules/lead/product-jenkins/dockercfg.tf
modules/lead/product-jenkins/versions.tf
modules/lead/sdm/main.tf
modules/lead/toolchain/artifactory.tf
modules/lead/toolchain/gitlab.tf
modules/lead/toolchain/versions.tf
modules/tools/kibana/versions.tf
modules/tools/kube-resource-report/main.tf
modules/tools/lab-partner/main.tf
stacks/environment-local/lead.tf
stacks/product-jenkins/versions.tf
stages/apps/lead/versions.tf
stages/apps/sharedsvc/versions.tf
stages/config/lead/versions.tf
stages/config/sharedsvc/versions.tf
tests/testdata/config/harbor/versions.tf

fix: upgrade providers to support darwin_amd64 and remove deprecated hashicorp/template provider

fix: upgrade providers to support darwin_amd64

---

modules/environment/aws/s3-website/main.tf
modules/environment/aws/s3-website/vars.tf
modules/environment/aws/s3-website/versions.tf
stages/cloud-provider/aws/sharedsvc/iam.tf
stages/cloud-provider/aws/sharedsvc/main.tf
stages/cloud-provider/aws/sharedsvc/s3-helm.tf

this will be accessible at https://charts.services.liatr.io

feat: setup s3 bucket as helm chart repository

---

modules/environment/aws/eks/iam.tf
modules/environment/aws/eks/main.tf
modules/environment/aws/github-runners-s3/main.tf
modules/environment/aws/iam/cluster-autoscaler/main.tf
modules/environment/aws/iam/external-dns/main.tf
modules/environment/aws/iam/github-runner-iam/main.tf
modules/environment/aws/iam/velero/main.tf
modules/lead/product-aws/product-base.tf
modules/lead/product-aws/variables.tf
modules/lead/product-base/database.tf
modules/tools/github-actions-runner-controller/main.tf
modules/tools/github-actions-runner-controller/runner-controller-values.tpl
modules/tools/vault-less-secure/main.tf
stacks/product-aws/main.tf
stacks/product-aws/variables.tf
stacks/product-test/main.tf
stages/apps/lead/operator-toolchain-values.tpl
stages/apps/lead/product-operator-values.tpl
stages/apps/lead/sdm.tf
stages/apps/lead/variables.tf
stages/cloud-provider/aws/lead/.terraform.lock.hcl
stages/cloud-provider/aws/lead/eks.tf
stages/cloud-provider/aws/lead/iam.tf
stages/cloud-provider/aws/lead/variables.tf
stages/cloud-provider/aws/lead/vault.tf

fix: update permission boundary for developer role
fix: update node group default configuration

feat: updates for upgrade to k8s 1.19

---

.github/workflows/terraform-validate.yml
modules/common/ca-issuer/main.tf
modules/common/ca-issuer/versions.tf
stages/apps/lead/.terraform.lock.hcl
stages/apps/sharedsvc/.terraform.lock.hcl
stages/apps/sharedsvc/elasticstack.tf

also fixes issue with new version of tls provider and add tls provider version requirement

feat: add elasticsearch to shared svc app stack
